### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by DamianMarzocca** [pdepjm/2024-tp0-presentacion-NicolasSchkurko#2]
Hola Nico, hay algún libro de ciencia ficción que recomiendes?.

**Comment by NicolasSchkurko** [comment]
El primer recopilado de los cuentos de ISAAC ASIMOV, fahrenheit 451 y 1984

**Comment by NicolasSchkurko** [comment]
El recopilado se llama "Cuentos completos I" (no me acordaba el nombre)
